// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqrzbjrmrugvlupjawkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcnpianJtcnVndmx1cGphd2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE3MjYzNzcsImV4cCI6MjA0NzMwMjM3N30.ya_KEvTX-wOukcpWfq0piQLBeHqCH7AA8cbV7eAmkJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});